/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    roles: Role;
    personas: Persona;
    programmes: Programme;
    stories: Story;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    personas: PersonasSelect<false> | PersonasSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    ('false' | 'none' | 'null') | false | null | ('en' | 'fr' | 'es' | 'ar') | ('en' | 'fr' | 'es' | 'ar')[];
  globals: {
    'site-copy': SiteCopy;
  };
  globalsSelect: {
    'site-copy': SiteCopySelect<false> | SiteCopySelect<true>;
  };
  locale: 'en' | 'fr' | 'es' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Hotel roles shown on the Growth Navigator map, ordered by level.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Stable id used by the map topology (e.g. "frontline"). Do not change once live.
   */
  slug: string;
  /**
   * 0 = frontline … 4 = general manager. Drives pyramid tiers.
   */
  level: number;
  label: string;
  overview: string;
  quote?: string | null;
  quoteAuthor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audience personas used to tailor the navigator panel copy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas".
 */
export interface Persona {
  id: number;
  /**
   * Stable id (e.g. "pathfinders"). Do not change once live.
   */
  slug: string;
  label: string;
  description: string;
  panelFocusSelf: string;
  panelFocusLeader: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Learning programmes on the map: core journeys and advanced (diploma) programmes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: number;
  /**
   * Stable id used by the map topology (e.g. "journey_supervisor"). Do not change once live.
   */
  slug: string;
  type: 'core' | 'advanced';
  /**
   * Role levels this programme spans on the map (0–4).
   */
  levels: number[];
  title: string;
  /**
   * One-line summary for map tooltips and sidebar.
   */
  mapSummary: string;
  leadsTo: string;
  whoItsFor: string;
  skillsDeveloped: string;
  whatToExpect: string;
  timeCommitment: string;
  nextStep: string;
  /**
   * Advanced programmes only.
   */
  whyChooseThis?: string | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Colleague success stories pinned to the map.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  slug: string;
  name: string;
  /**
   * e.g. "Housekeeping → Supervisor → Manager"
   */
  pathDescription: string;
  shortStory: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  slug: string;
  question: string;
  answer: string;
  /**
   * Display order, lowest first.
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'personas';
        value: number | Persona;
      } | null)
    | ({
        relationTo: 'programmes';
        value: number | Programme;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  slug?: T;
  level?: T;
  label?: T;
  overview?: T;
  quote?: T;
  quoteAuthor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personas_select".
 */
export interface PersonasSelect<T extends boolean = true> {
  slug?: T;
  label?: T;
  description?: T;
  panelFocusSelf?: T;
  panelFocusLeader?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  levels?: T;
  title?: T;
  mapSummary?: T;
  leadsTo?: T;
  whoItsFor?: T;
  skillsDeveloped?: T;
  whatToExpect?: T;
  timeCommitment?: T;
  nextStep?: T;
  whyChooseThis?: T;
  quote?: T;
  quoteAuthor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  pathDescription?: T;
  shortStory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  slug?: T;
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Campaign copy for the Room to Grow page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy".
 */
export interface SiteCopy {
  id: number;
  strapline: {
    headline: string;
    intro: string;
  };
  introBlock: {
    internalComms: string;
    ihgUniversityExplanation: string;
    journeyStartsHere: string;
  };
  intentSelector: {
    question: string;
    microcopy: string;
    options?:
      | {
          value: 'selfGrowth' | 'developingTeam' | 'learnAbout';
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  pathAiConfig: {
    sectionTitle: string;
    inputPlaceholder: string;
    quickPrompts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  sellingPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  managerGuidance?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  leaderActionSteps?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Questions that map answers to personas without using internal labels.
   */
  personaQualifier?: {
    questions?:
      | {
          questionId: string;
          question: string;
          options?:
            | {
                label: string;
                /**
                 * Must match a persona slug.
                 */
                personaSlug: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-copy_select".
 */
export interface SiteCopySelect<T extends boolean = true> {
  strapline?:
    | T
    | {
        headline?: T;
        intro?: T;
      };
  introBlock?:
    | T
    | {
        internalComms?: T;
        ihgUniversityExplanation?: T;
        journeyStartsHere?: T;
      };
  intentSelector?:
    | T
    | {
        question?: T;
        microcopy?: T;
        options?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  pathAiConfig?:
    | T
    | {
        sectionTitle?: T;
        inputPlaceholder?: T;
        quickPrompts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  sellingPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  managerGuidance?:
    | T
    | {
        text?: T;
        id?: T;
      };
  leaderActionSteps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  personaQualifier?:
    | T
    | {
        questions?:
          | T
          | {
              questionId?: T;
              question?: T;
              options?:
                | T
                | {
                    label?: T;
                    personaSlug?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}